name: git-commit
description: A Buildkite plugin to commit and push the results of a command to a git repository.
author: https://github.com/reidab
requirements: []
configuration:
  properties:
    add:
      type: string
    branch:
      type: string
    create-branch:
      type: boolean
    message:
      type: string
    remote:
      type: string
    user:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
