steps:
  - label: ":hammer: Test"
    plugins:
      docker-compose#v1.3.1:
        run: tests
  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v1.0.0:
        name: thedyrt/git-commit
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**
